name: Example Workflow
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'src/demo.env'
    branches-ignore:    
      - 'develop'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
